[project]
name = "omr-opencv"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "numpy>=2.2.5",
    "opencv-python-headless>=4.11.0.86",
    "python-multipart>=0.0.20",
]
